name: ed_tech
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  gap: ^3.0.1
  provider: ^6.1.2
  shared_preferences: ^2.5.1
  http: ^1.3.0
  firebase_auth: ^5.4.2
  google_sign_in: ^6.2.2
  timeago: ^3.7.0
  duration_picker: ^1.2.0
  image_picker: ^1.1.2
  flutter_spinkit: ^5.2.1
  awesome_snackbar_content: ^0.1.5
  flutter_local_notifications: ^18.0.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
